language: minimal

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck

before_script:
 - /home/travis/.luarocks/bin/luacheck . -q

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/ # v1.0.0 or 1.0.0 etc

notifications:
  email:
    on_success: never
    on_failure: always
